.TH DPKG.CFG 5 "Februaio 2002" "Debian Project" "dpkg suite"
.SH NOME
dpkg.cfg \- file di configurazione di dpkg
.SH DESCRIZIONE
Questo file contiene le opzioni predefinite per dpkg. Ogni riga
contiene un singola opzione che è esattamente la stessa di una
opzione normale della riga di comando per dpkg eccetto per i "trattini"
iniziali che qui non vengono usati. I commenti 
sono permessi se si inizia una riga con un segno "\fB#\fR" (hash). 
.SH FILE
.I /etc/dpkg/dpkg.cfg
~/.dpkg.cfg
.SH AUTORE
Vedere il file \fB/usr/share/doc/dpkg/THANKS\fP per la lista delle persone
che hanno contribuito a \fBdpkg\fP.
Traduzione e adattamenti in Italiano a cura di Hugh Hartmann 
<hhartmann@libero.it>, Revisione a cura di Beatrice Torracca.
.SH VEDERE ANCHE
.BR dpkg (8)
