.TH "dselect.cfg" "5" "28 febbraio 2006" "Debian Project" "dpkg suite"
.SH "NOME"
dselect.cfg \- file di configurazione di dselect 
.
.SH "DESCRIZIONE"
Questo file contiene le opzioni predefinite per dselect. Ogni riga contiene una
singola opzione che è esattamente la stessa di una normale riga di comando
per dselect, eccetto per il "trattino" iniziale che qui non è
usato. I commenti sono permessi iniziando una riga con il segno del cancelletto
("\fB#\fR").
.
.SH "FILE"
.I /etc/dpkg/dselect.cfg
.br 
.I ~/.dselect.cfg
.
.SH "AUTORE"
Vedere \fI/usr/share/doc/dpkg/THANKS\fP per l'elenco delle persone 
che hanno contribuito a \fBdselect\fP.
Traduzione e adattamenti in italiano a cura di Hugh Hartmann 
<hhartmann@libero.it>. Revisione a cura di Beatrice Torracca.
.
.SH "VEDERE ANCHE"
.BR dselect (1).
