.TH DSELECT.CFG 5 "Febraio 2002" "Debian Project" "dpkg suite"
.SH NOME
dselect.cfg \- file di configurazione di dselect 
.SH DESCRIZIONE
Questo file contiene le opzioni predefinite per dselect. Ogni riga
contiene una singola opzione che è esattamente la stessa di una
normale riga di comando per dselect eccetto per il "trattino" iniziale
che qui non è usato. I commenti sono permessi se si inizia
una riga con un segno ("\fB#\fR") (hash).
.SH FILE
.I /etc/dpkg/dselect.cfg
~/.dselect.cfg
.SH AUTORE
Vedere il file \fB/usr/share/doc/dpkg/THANKS\fP per la lista delle persone 
che hanno contribuito a \fBdselect\fP.
Traduzione e adattamenti in Italiano a cura di Hugh Hartmann 
<hhartmann@libero.it>. Revisione a cura di Beatrice Torracca.
.SH VEDERE ANCHE
.BR dselect (8)
