.\" Copyright (c) 1993 Michael Haardt (michael@moria.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified Sat Jul 24 16:57:14 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Settembre 1996
.\" Aggiornamento a man pages 2.38 di Giulio Daprelà <giulio@pluto.it>
.\" agosto 2006
.\" Aggiornamento a man pages 2.68 di Elisabetta Galli <lab@kkk.it>
.\" novembre 2007
.\"
.TH INTRO 4 "23 ottobre 2007" "Linux" "Linux Programmer's Manual"
.SH NOME
intro \- Introduzione ai file speciali
.SH DESCRIZIONE
La sezione 4 del manuale descrive i file speciali (dispositivi).
.SH FILE
/dev/* \(em file di dispositivo.
.SH NOTE
.SS Autori e condizioni di Copyright
Si veda l'intestazione del sorgente della pagina di manuale per l'autore e le
condizioni di copyright.
Si noti che questi possono differire da pagina a pagina.
.SH "VEDERE ANCHE"
.BR standards (7)
